### ISSUE TITLE
A quick way to get the dankest of memes

### ISSUE THREAD

**Issue by Detry322** [techx/hackmit-hackbot#4]
we need this feature to continue operating as a club

**Comment by mysticuno** [comment]
Not as a club, but as a startup that only recruits the dankest pepes

**Comment by ehzhang** [comment]
Quip had a meme generator with the syntax of like:
Meme @ehzhang "top text" "bottom text" and outputs a meme using their prof pic

**Comment by Detry322** [comment]
Sometimes i want a dank meme from reddit and i want hackbot to give it to me

but we could also do like hackbot meme <search> <top text> <bottom text>

and it makes a meme using the image search and top/bottom text
